"""Configuration dataclasses.

Two schemas live here side by side:

- The legacy ``AppConfig`` tree (GUI / launchd watcher flow).
- The v2 ``Config`` tree (``[app]`` / ``[advanced]`` / ``[transcription]`` /
  ``[summary]``) used by the backend-abstraction pipeline.

Parsing/loading lives in ``loader.py``; both are re-exported from the package
``__init__`` so ``from app.config import ...`` keeps working unchanged.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

CONFIG_PATH = Path.home() / ".config" / "audio-transcriptor" / "config.toml"

_DEFAULT_EXTENSIONS: frozenset[str] = frozenset({".wav", ".mp3"})

_DEFAULT_PR_BODY_TEMPLATE = (
    "Auto-generated by audio-transcriptor.\n\n"
    "- transcript: {transcript_name}\n"
    "- minutes: {minutes_name}\n"
)


# --------------------------------------------------------------------------- #
# Legacy schema (GUI / launchd watcher)
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class MinutesConfig:
    enabled: bool = True
    ollama_host: str = "http://localhost:11434"
    model: str = "gemma4"
    prompt_language: str = "ja"
    max_input_chars: int = 30000
    request_timeout_seconds: float = 600.0
    num_ctx: int = 32768


@dataclass(frozen=True)
class AutoPRConfig:
    enabled: bool = False
    repo_path: Path = field(default_factory=lambda: Path("~/path/to/your-repo"))
    transcript_subdir: str = ""
    minutes_subdir: str = ""
    default_branch: str = "main"
    branch_prefix: str = "auto-transcript/"
    commit_message_template: str = "add transcript for {date}"
    pr_title_template: str = "add transcript for {date}"
    pr_body_template: str = _DEFAULT_PR_BODY_TEMPLATE
    gh_repo: str = ""


@dataclass(frozen=True)
class AppConfig:
    language: str = "ja"
    model: str = "medium"
    watch_dir: Path = field(default_factory=lambda: Path.home() / "Downloads")
    extensions: frozenset[str] = _DEFAULT_EXTENSIONS
    file_stability_seconds: float = 3.0
    trash_source_after_success: bool = True
    minutes: MinutesConfig = field(default_factory=MinutesConfig)
    auto_pr: AutoPRConfig = field(default_factory=AutoPRConfig)


# --------------------------------------------------------------------------- #
# v2 backend-abstraction schema
#
# The user-facing surface is just `[app] mode = "auto"`; everything else is
# developer/advanced tuning.
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class AppSection:
    mode: str = "auto"
    language: str = "ja-JP"
    output_directory: str = "same_as_audio"


@dataclass(frozen=True)
class AdvancedSection:
    transcription_backend: str = "auto"
    summary_backend: str = "auto"
    apple_transcribe_path: str = ""
    apple_summarize_path: str = ""


@dataclass(frozen=True)
class TranscriptionSection:
    model: str = "medium"
    vad_enabled: bool = True


@dataclass(frozen=True)
class OllamaSummaryConfig:
    host: str = "http://localhost:11434"
    model: str = "gemma4"
    num_ctx: int = 32768


@dataclass(frozen=True)
class SummarySection:
    output_language: str = "ja"
    include_evidence: bool = True
    max_input_chars: int = 30000
    request_timeout_seconds: float = 600.0
    ollama: OllamaSummaryConfig = field(default_factory=OllamaSummaryConfig)


@dataclass(frozen=True)
class Config:
    app: AppSection = field(default_factory=AppSection)
    advanced: AdvancedSection = field(default_factory=AdvancedSection)
    transcription: TranscriptionSection = field(default_factory=TranscriptionSection)
    summary: SummarySection = field(default_factory=SummarySection)
