from __future__ import annotations

import logging
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)

CONFIG_PATH = Path.home() / ".config" / "mlx-audio-transcriptor" / "config.toml"

_DEFAULT_EXTENSIONS: frozenset[str] = frozenset({".wav", ".mp3"})


@dataclass(frozen=True)
class MinutesConfig:
    enabled: bool = True
    ollama_host: str = "http://localhost:11434"
    model: str = "gemma4"
    prompt_language: str = "ja"
    max_input_chars: int = 30000
    request_timeout_seconds: float = 600.0
    num_ctx: int = 32768


_DEFAULT_PR_BODY_TEMPLATE = (
    "Auto-generated by mlx-audio-transcriptor.\n\n"
    "- transcript: {transcript_name}\n"
    "- minutes: {minutes_name}\n"
)


@dataclass(frozen=True)
class AutoPRConfig:
    enabled: bool = False
    repo_path: Path = field(default_factory=lambda: Path("~/path/to/your-repo"))
    transcript_subdir: str = ""
    minutes_subdir: str = ""
    default_branch: str = "main"
    branch_prefix: str = "auto-transcript/"
    commit_message_template: str = "add transcript for {date}"
    pr_title_template: str = "add transcript for {date}"
    pr_body_template: str = _DEFAULT_PR_BODY_TEMPLATE
    gh_repo: str = ""


@dataclass(frozen=True)
class AppConfig:
    language: str = "ja"
    model: str = "medium"
    watch_dir: Path = field(default_factory=lambda: Path.home() / "Downloads")
    extensions: frozenset[str] = _DEFAULT_EXTENSIONS
    file_stability_seconds: float = 3.0
    trash_source_after_success: bool = True
    minutes: MinutesConfig = field(default_factory=MinutesConfig)
    auto_pr: AutoPRConfig = field(default_factory=AutoPRConfig)


def _parse_minutes(data: dict) -> MinutesConfig:
    defaults = MinutesConfig()
    return MinutesConfig(
        enabled=bool(data.get("enabled", defaults.enabled)),
        ollama_host=str(data.get("ollama_host", defaults.ollama_host)),
        model=str(data.get("model", defaults.model)),
        prompt_language=str(data.get("prompt_language", defaults.prompt_language)),
        max_input_chars=int(data.get("max_input_chars", defaults.max_input_chars)),
        request_timeout_seconds=float(
            data.get("request_timeout_seconds", defaults.request_timeout_seconds)
        ),
        num_ctx=int(data.get("num_ctx", defaults.num_ctx)),
    )


def _parse_auto_pr(data: dict) -> AutoPRConfig:
    defaults = AutoPRConfig()
    repo_path_raw = data.get("repo_path")
    if repo_path_raw:
        repo_path = Path(str(repo_path_raw)).expanduser()
    else:
        repo_path = defaults.repo_path
    return AutoPRConfig(
        enabled=bool(data.get("enabled", defaults.enabled)),
        repo_path=repo_path,
        transcript_subdir=str(data.get("transcript_subdir", defaults.transcript_subdir)),
        minutes_subdir=str(data.get("minutes_subdir", defaults.minutes_subdir)),
        default_branch=str(data.get("default_branch", defaults.default_branch)),
        branch_prefix=str(data.get("branch_prefix", defaults.branch_prefix)),
        commit_message_template=str(
            data.get("commit_message_template", defaults.commit_message_template)
        ),
        pr_title_template=str(data.get("pr_title_template", defaults.pr_title_template)),
        pr_body_template=str(data.get("pr_body_template", defaults.pr_body_template)),
        gh_repo=str(data.get("gh_repo", defaults.gh_repo)),
    )


def _parse(data: dict) -> AppConfig:
    defaults = AppConfig()

    language = str(data.get("language", defaults.language))
    model = str(data.get("model", defaults.model))

    watch_dir_raw = data.get("watch_dir")
    if watch_dir_raw:
        watch_dir = Path(str(watch_dir_raw)).expanduser()
    else:
        watch_dir = defaults.watch_dir

    ext_raw = data.get("extensions")
    if ext_raw:
        exts = [e.lower() if e.startswith(".") else f".{e.lower()}" for e in ext_raw]
        extensions = frozenset(exts)
    else:
        extensions = defaults.extensions

    stability = float(data.get("file_stability_seconds", defaults.file_stability_seconds))
    trash = bool(data.get("trash_source_after_success", defaults.trash_source_after_success))

    minutes_raw = data.get("minutes")
    minutes = _parse_minutes(minutes_raw) if isinstance(minutes_raw, dict) else MinutesConfig()

    auto_pr_raw = data.get("auto_pr")
    auto_pr = _parse_auto_pr(auto_pr_raw) if isinstance(auto_pr_raw, dict) else AutoPRConfig()

    return AppConfig(
        language=language,
        model=model,
        watch_dir=watch_dir,
        extensions=extensions,
        file_stability_seconds=stability,
        trash_source_after_success=trash,
        minutes=minutes,
        auto_pr=auto_pr,
    )


def load_config(path: Path | None = None) -> AppConfig:
    path = path or CONFIG_PATH
    if not path.exists():
        return AppConfig()
    try:
        raw = path.read_bytes()
        data = tomllib.loads(raw.decode("utf-8"))
    except (OSError, tomllib.TOMLDecodeError, UnicodeDecodeError) as e:
        logger.warning("failed to read config %s: %s — falling back to defaults", path, e)
        return AppConfig()
    return _parse(data)
